services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    restart: unless-stopped
  backend:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on: postgres