services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    restart: unless-stopped
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_DB_HOST: postgres
      RAILS_DB_USER: postgres
      RAILS_ENV: production
      RAILS_DB_PASSWORD: password
    restart: unless-stopped
    depends_on: 
     - postgres