default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DB_HOST") { '0.0.0.0' } %>
  user: <%= ENV.fetch("RAILS_DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") { 'password' } %>
development:
  <<: *default
  database: promo_engine_development
test:
  <<: *default
  database: promo_engine_test
production:
  <<: *default
  adapter: postgresql
  database: promo_engine_production
